# Generated by Django 2.1 on 2018-12-06 02:54

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20181205_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['user__userextension__slug, title']),
        ),
    ]
