# Generated by Django 2.1 on 2018-12-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0009_userextension_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='user_image',
            field=models.ImageField(blank=True, default='pic_folder/None/no-img.jpg', null=True, upload_to='images/'),
        ),
    ]
