# Generated by Django 2.1 on 2018-12-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0010_auto_20181221_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='user_image',
            field=models.ImageField(blank=True, default='journals/images/no-img.png', upload_to='profile_image'),
        ),
    ]
