# Generated by Django 2.1 on 2018-12-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0012_auto_20181222_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='user_image',
            field=models.ImageField(blank=True, default='profile_image/no-img.png', height_field=300, upload_to='profile_image', width_field=300),
        ),
    ]
