# Generated by Django 2.1 on 2018-12-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0013_auto_20181222_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='user_image',
            field=models.ImageField(blank=True, default='profile_image/no-img.png', upload_to='profile_image'),
        ),
    ]
